jeremyckahn/farmhand

package-lock.json
package.json
src/Farmhand.js
src/Farmhand.sass
src/Farmhand.test.js
src/components/LogView/LogView.js
src/components/LogView/LogView.test.js
src/components/NotificationSystem/NotificationSystem.js
src/components/NotificationSystem/NotificationSystem.test.js
src/components/NotificationSystem/index.js
src/event-handlers.js
src/event-handlers.test.js
src/reducers.js
src/reducers.test.js

Reduce notification spam

---

src/Farmhand.js
src/components/AppBar/AppBar.js
src/components/AppBar/AppBar.sass
src/components/AppBar/AppBar.test.js
src/components/SettingsView/SettingsView.js
src/components/SettingsView/SettingsView.test.js
src/constants.js
src/event-handlers.js
src/reducers.js
src/reducers.test.js

Feature: Hide notifications toggle

---

src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.sass
src/utils.js

Level up indicator (for #44)

---

api-etc/constants.js
api/get-market-data.js
src/Farmhand.js
src/common/constants.js
src/event-handlers.js
src/templates.js

Feature: Room limits

---

.env
package-lock.json
package.json
src/Farmhand.js
src/components/Navigation/Navigation.js
src/components/Navigation/Navigation.test.js
src/components/OnlinePeersView/OnlinePeersView.js
src/components/OnlinePeersView/OnlinePeersView.sass
src/components/OnlinePeersView/OnlinePeersView.test.js
src/components/OnlinePeersView/index.js
src/constants.js
src/enums.js
src/event-handlers.js
src/reducers.js
src/utils.js

Feature: Show peer player stats

---

src/Farmhand.js
src/components/Item/Item.js
src/components/Plot/Plot.js
src/components/Plot/Plot.sass
src/components/Plot/Plot.test.js
src/constants.js
src/data/__mocks__/items.js
src/data/items.js
src/enums.js
src/event-handlers.js
src/img/index.js
src/index.js
src/reducers.js
src/reducers.test.js
src/test-utils/index.js
src/utils.js
src/utils.test.js

- Adds male Rainbow Cows
- Male Rainbow Cows produce Rainbow Fertilizer
- Rainbow Fertilizer automatically replants crops when harvested
- Rainbow Fertilizer automatically replaces Scarecrows from inventory when they are destroyed by a storm

Feature: Rainbow Fertilizer

---

CONTRIBUTORS.md

@lstebner are you good with me adding this?

chore [closes #78] Add CONTRIBUTORS.md

---

src/Farmhand.js
src/utils.js
src/utils.test.js

changes getAvailbleShopInventory to getAvailableShopInventory

[closes #91] chore: fix typo

---

.github/pull_request_template.md
.github/workflows/run-release.yml

This PR assumes that https://github.com/jeremyckahn/farmhand/runs/2876457694?check_suite_focus=true is broken due to a missing branch name under the github push action
¯\_(ツ)_/¯ we hope this works

Attempt to fix broken CI deployment

---

.github/pull_request_template.md
.github/workflows/notify-discord-about-update.yml
README.md

I made a few tweaks that we've discussed recently. Let me know what you think of the PR template!

Improve GitHub actions

---

CONTRIBUTORS.md
src/components/Home/Home.js

It updates the developer note on the Home screen to be more reflective of the state of the project and the people building it. It also removes the payment links.
Read and proofread the copy changes.

Update developer note on Home screen

---

src/Farmhand.js
src/components/Home/Home.js
src/components/KeybindingsView/KeybindingsView.js
src/components/KeybindingsView/KeybindingsView.sass
src/components/KeybindingsView/KeybindingsView.test.js
src/components/KeybindingsView/index.js
src/components/Navigation/Navigation.js
src/enums.js

It adds onboard documentation for in-game keyboard shortcuts. (#170)
Press `shift + ?` anywhere in the game.

Keyboard shortcut info

---

src/Farmhand.js
src/templates.js

For #187, this PR broadcasts market changes to the online peer room.
Set up two online peers, buy/sell various crops or seeds on one peer and end the day, and then observe the message on the other peer.

Broadcast price changes

---

src/components/Shop/Shop.js

Minor change in textual content of the Shop, changed the word Storge to Storage.
N/A
N/A

Fixes a typo

---

.env
src/components/Shop/Shop.js
src/components/Shop/Shop.test.js

It enables the Mining feature for all environments! While the Mining feature is not yet 100% feature complete, it's stable and playable enough for a soft launch. Once we wrap up the [remaining features](https://github.com/jeremyckahn/farmhand/projects/5), we should share the update more broadly and hype folks up a bit.
Go to the preview URL (https://farmhand-git-jeremyckahn-enable-mining-jeremyckahn.vercel.app/) and ensure that the Smelter is available for purchase, and that any other Mining-specific features are available and working.
I'm planning to ship this to Prod as soon as it's approved and merged.

Enable mining

---

package-lock.json
package.json

This PR updates Trystero, the library used for peer-to-peer to communication, to it's latest version (0.10.0). Trystero has had some significant updates recently: https://github.com/dmotz/trystero/commits/main
I've noticed some flakiness with peer connections lately, so hopefully this will help.
Go online successfully in the game.
Preview URL: https://farmhand-git-jeremyckahn-update-trystero-jeremyckahn.vercel.app/
There isn't a great way to test this without putting it into production, really. I think we just have to ship it and hope for the best. :grimacing:

Update Trystero to 0.10.0

---

src/components/Home/Home.js
src/img/index.js

It adds a promotional message to the Home screen to direct players to Farmhand Go!
Proofread the copy and make sure it has no errors and has decent messaging.
I'm not married to the copy here, I just kinda winged (wung?) it. I'm open to suggestions for how to improve it!

feat: Add Farmhand Go! blurb on Home screen

---

.gitignore
src/components/CowPenContextMenu/CowPenContextMenu.js
src/data/shop-inventory-cow.js
src/utils.js

Resolves issue #268, preventing cow shop items from being resold for profit
Selling cow feed or hugging machines

Issue #268 - Prevent cow shop items from being re-sold for profit

---

README.md

It adds a section to the README to define coding conventions.
Proofread the new copy.
I expect this will grow over time, I just wanted to get a start on documenting this (and work on my backlog of TODOs!).

docs: Define coding conventions

---

.github/workflows/ci.yml
.github/workflows/run-release.yml
.gitpod.yml
README.md
src/data/achievements.js

This PR implements the "Spooky Pumpkin Patch" achievement. If the player sells 10,000 Jack-o'-lanterns, they will receive 100 Scarecrows.
Sell 10,000 Jack-o'-lanterns and observe that the achievement is completed and that the player is rewarded with 100 Scarecrows.

feat: Implement "Spooky Pumpkin Patch" achievement

---

src/data/achievements.js
src/setupTests.js

This PR implements the "Halloween Harvest" achievement. When the player plays Farmhand in October, they will receive 150 Jack-o'-lanterns.
Open the game in October and confirm that the player is given 150 Jack-o'-lanterns.

feat: Halloween Harvest achievement

---

package-lock.json
package.json
src/game-logic/reducers/forRange.js

Per [my comment](https://github.com/jeremyckahn/farmhand/pull/357#discussion_r1058602822) in #357, this PR updates the JSDoc annotations for the `forRange` reducer.

docs: Update `forRange` JSDoc

---

package-lock.json
package.json

This PR fixes broken cow images by using [a maintained version of zlib](https://www.npmjs.com/package/browserify-zlib).
Make sure cow images render.

hotfix: Use zlib@npm:browserify-zlib

---

CONTRIBUTORS.md

adds gdorangee to the contributors list

add 'gdorangee' to contributors

---

package-lock.json

This PR rebuilds `package-lock.json` by running `rm package-lock.json && npm i`.
Ensure that all the CI checks pass and the preview deployment is successful.

chore(package): Rebuild package-lock.json

---

api-etc/utils.js
api/publish-global-market-values-to-discord.js
src/common/services/randomNumber.test.js
src/common/utils.test.js
src/components/AccountingView/AccountingView.js
src/components/AccountingView/AccountingView.test.js
src/components/Achievement/Achievement.test.js
src/components/AchievementsView/AchievementsView.js
src/components/AnimatedNumber/AnimatedNumber.js
src/components/AppBar/AppBar.js
src/components/Cellar/CellarInventoryTabPanel.js
src/components/ContextPane/ContextPane.js
src/components/CowCard/CowCard.js
src/components/CowCard/CowCard.test.js
src/components/CowPen/CowPen.js
src/components/CowPen/CowPen.test.js
src/components/CowPenContextMenu/CowPenContextMenu.js
src/components/Farmhand/Farmhand.context.js
src/components/Farmhand/Farmhand.js
src/config.js
src/data/achievements.js
src/index.js
src/utils/index.js
tsconfig.json
vite.config.js

There are two themes spread across three commits for this PR:
- A variety of type fixes:
- https://github.com/jeremyckahn/farmhand/commit/13c5e112406d1542567cca92116f5a8b5b35d365
- https://github.com/jeremyckahn/farmhand/commit/06db008d16e540eff0f7bc55576eaf50c7cfd3b3
- I don't recommend spending too much time reviewing these. It's pretty unexciting and not a great use of reviewer time. A quick skim should be sufficient.
- A regression fix (from #509) for multiplayer where the incorrect connection strategy was being used: https://github.com/jeremyckahn/farmhand/commit/b7c5d16ce9d0c377e2a8fea81be651d94ea22ca0
- This is the commit that's actually worth reviewing

fix(multiplayer): Use torrent strategy for Trystero

---

src/components/Farmhand/Farmhand.js

This PR refactors `incrementDay` to hopefully avoid race conditions that could conceivably result from stale React state.
ℹ️ This is pretty extensive testing plan and I'm not expecting anyone to actually run through all of the scenarios. A spot check of behavior related to the "End Day" button should be sufficient and appreciated, as what's here is mostly covered by the automated tests.
<details>
<summary>
Scenarios to test
</summary>
* **Starting a New Day (First Day):**
* **Advancing Subsequent Days:**
* **Online Mode - Market Impact:**
* **Online Mode - Server Connection Issues:**
* **Offline Mode - Market Changes:**
* **Automatic Harvesting (Combine Enabled):**
* **No Automatic Harvesting (Combine Disabled):**
* **End-of-Day Notifications:**
**Field, Crops & Environment:**
* **Crop …

refactor(incrementDay): Use functional `setState`

---

e2e/Dockerfile.farmhand

Fixes an E2E test infrastructure breakage: https://github.com/jeremyckahn/farmhand/actions/runs/18315282771/job/52154786309#step:9:235 
Ensure the E2E tests pass.

fix(e2e): Use latest `curl`
