jeremyckahn/farmhand

- src/components/Navigation/Navigation.js
updated icon used for Farmer's Log, Stats, Achievements and Bank  Account
before this change:
after:
> refactor [#67] new icons for some navigation elements

- src/components/Achievement/Achievement.js
a recent change to the navigation icons caused this one to no longer
match. this change updates the icon, and also changes the 'completed'
state to be completely CSS based instead of using another icon.
current mismatched version:
updated states:
> fix [closes #74] updating icons in Achievement component

- src/components/CowPen/CowPen.js
- src/components/CowPen/CowPen.sass
- src/components/CowPen/CowPen.test.js
- src/constants.js
- src/enums.js
cows currently face right all the time, but this change adds some
logic so that when they are moving left, they also look to the left.
this was doing with CSS using transform, so it also inherited a nice
little transition property that adds some animation to the whole
thing.
additionally: it was noticed that X position was being applied as the
`top` style and Y as the `left` so this was flipped which seems more
expected.
> [closes #95] feat: make cows look in moove direction

- CONTRIBUTORS.md
- src/components/Item/Item.js
- src/components/QuantityInput/QuantityInput.js
- src/components/Recipe/Recipe.js
Sorry this is somewhat of an opinionated change. But I found it annoying that I couldn't clear the default value of the controlled component completely when writing out a desired amount. i.e. if the value amount was `1` and I wanted `50` I'd have to start typing my desired amount and clear the value. So I am proposing we just clear the quantity input value on focus.
Select the Quantity Input for both buying and selling an item and notice that when you select the input the previous default value clears. The Buy/Sell button should be disabled if an undefined value is current set.
I could perhaps make the disabled item button check a bit cleaner but for now I just added to the conditional to check if the purchase or sell quantity isn't defined.
> QuantityInput: clear input onFocus

- .github/workflows/ci.yml
- .github/workflows/notify-discord-about-update.yml
- .github/workflows/run-release.yml
- README.md
This PR brings Farmhand into the present! This shouldn't affect how we do anything, it just modernizes our branch structure a bit.
I have already created the [new `main` branch](https://github.com/jeremyckahn/farmhand/tree/main) and will delete `master` once this is merged.
> Target `main` branch instead of `master`

- src/reducers.js
- src/reducers.test.js
Fixes #42. This PR keeps multiple crow attacks from spamming the player by grouping them all into a single batch notification.
> Group crow notifications

- README.md
- src/Farmhand.js
- src/config.js
- src/index.js
It extends #136 (for #133) by allowing players to enable feature flags through URL query params.
Manually add query params as described by the new documentation to the Preview environment's URL and see that they are provided as `props` to the `Farmhand` component in the React DevTools.
> Add support for enabling features via query params

- src/components/Item/Item.js
- src/components/Item/Item.test.js
- src/data/shop-inventory.js
the "I am Rich" achievement PR introduced an exploitable bug by
affecting the price of seeds, and other items sold from the shop.
players could buy these and instantly resell them for a steady profit.
this PR patches that hole by checking to see if an item is sold in the
shop before applying the adjustment to the value. this should help
prevent this bug from popping back up in the future.
To test this change you need to achieve one of the "i am rich" achievements; so sell at least $500,000 worth of goods. Then check the resale price of seeds, fertilizer, and the scarecrow. These should all stay consistent as to what they were before, even though crops and workshop items start to get boosted.
This logic being wrapped up in this component makes it very cumbersome to test. We should probably …
> fix: [closes #140] avoid increasing value of items sold from the shop

- src/data/achievements.js
- src/data/achievements.test.js
the gold-digger achievement was not behind the MINING feature flag and was unlockable in production, even though the shovel didn't unlock. this fixes that bug and only adds the achievement when the feature is actually enabled.
- go to production farmhand game
- open the achievements list
- find "gold digger" at the bottom
- next, go to vercel preview URL
- open the achievement list
- notice the 'gold digger' achievement is no longer there!
> fix: put gold-digger achievement behind feature flag

- src/components/Navigation/Navigation.js
For #175, this PR adds `aria-describedby` and `aria-labelledby` attributes to the Keyboard Shortcuts modal. Since Farmhand's modals are implemented generically, this also enhances all of the other modals as well!
References for implementation: 
- https://github.com/jeremyckahn/farmhand/issues/175#issuecomment-899082811
- https://material-ui.com/components/modal/#accessibility
I'm actually not sure how this can be validated and would appreciate some help with determining this. So far I've just made our DOM look like the suggested solutions, but I don't know how to verify that it's providing the intended experience to relevant users.
Here's how the DOM for this looks:
> Modal accessibility enhancements

- public/index.html
- src/components/Home/Home.js
This PR adds Google Analytics tracking so that informed development decisions can be made based on user behavior.
Load the page and observe that a `POST https://www.google-analytics.com/g/collect` request is made. This may fail depending on the browser or user's settings, but that's okay.
I went back and forth a lot on adding this. I took a lot of pride in Farmhand _not_ having this functionality, but it's become clear that we can't get a remotely accurate picture of how much the game is played or how people are finding it. The better we can understand our users in aggregate, the more effectively we can grow and serve the community.
> Add Google Analytics

- src/components/KeybindingsView/KeybindingsView.js
- src/components/Shop/Shop.js
For #189 and a bug report on Discord, this renames the "Field Tools" tab in the shop to "Supplies" and also fixes a keyboard shortcut label.
> Text updates

- src/Farmhand.sass
- src/components/Plot/Plot.sass
- src/components/QuickSelect/QuickSelect.sass
- src/styles/utils.sass
For #114, this PR gives sprites throughout the game a slight drop shadow.
Open the preview URL (https://farmhand-git-jeremyckahn-114sprite-shadows-jeremyckahn.vercel.app/), navigate around the various screens, and observe the new drop shadow styles.
How do folks feel about this aesthetic change? Is the shadow too strong? Is it even better than the flat style it replaces?
> Add sprite shadows

- src/components/AppBar/AppBar.js
- src/components/ContextPane/ContextPane.sass
- src/components/CowPenContextMenu/CowPenContextMenu.js
- src/components/CowPenContextMenu/CowPenContextMenu.sass
- src/components/CowPenContextMenu/TabPanel/index.js
- src/components/Stage/Stage.sass
- src/styles/utils.sass
For #200, this PR redesigns the Cows menu to be tab-based for easier navigation.
This is a rather noisy diff, but there's not much logic being added that hasn't been seen already in #185 and #183. A lot got moved around to make sense with tabs, but new logic is minimal.
Purchase a Cow Pen and do any number of your standard cow operations (buy/sell cows, feed, hugging machines).
> Tabify cow menu

- package-lock.json
- package.json
- src/components/Plot/Plot.js
- src/components/Plot/Plot.rtl.test.js
- src/components/Plot/Plot.sass
- src/components/Plot/Plot.test.js
- src/data/__mocks__/items.js
- src/img/__mocks__/index.js
- src/test-utils/index.js
- src/utils.js
- src/utils.test.js
For #199, this PR adds an animation to indicate what the user has just dug up.
A lot of the changes in this PR are part of the ongoing effort to adopt React Testing Library. Rather than updating all of the old test files related to this change, this PR adds `Plot.rtl.test.js` for React Testing Library-specific changes.
Go to https://farmhand-git-jeremyckahn-199mining-animation-jeremyckahn.vercel.app/?enable_MINING=true, unlock the shovel, and dig up some items from the field.
https://user-images.githubusercontent.com/366330/133005441-ed90de71-5498-435d-8c3f-26acea8af377.mp4
> Mining animation

- public/index.html
This PR fixes analytics tracking for https://www.farmhand.life/. Presently only analytics for https://jeremyckahn.github.io/farmhand/ are being recorded.
Ship it and see if the data shows up in the Google Analytics dashboard. :man_shrugging:
> [#214] Fix Google Analytics for www.farmhand.life

- .github/workflows/ci.yml
- .github/workflows/run-release.yml
- README.md
- package-lock.json
- package.json
This PR fixes breaking builds in Vercel, which we need for deploys. I'm not really sure what changed, but it seems to be something on Vercel's side. `piskel-cli` is an optional development dependency, and it sub-depends on PhantomJS. PhantomJS has long been a source of pain when installing Farmhand. It tends to not install correctly on a lot of environments, which causes the entire project installation to fail.
This PR should hopefully provide a long term fix by moving `piskel-cli` to the [`optionalDependencies` list](https://betterprogramming.pub/what-are-npms-optional-dependencies-and-when-should-we-use-them-796a6a964e73).
I think this passing build should sufficiently validate this change: https://vercel.com/jeremyckahn/farmhand/HTdUa4tjXEvQAnT9Tq9DkKWqTNVt
You can also do `rm -rf …
> Make piskel-cli optional

- src/Farmhand.js
- src/components/Toolbelt/Toolbelt.js
- src/components/Toolbelt/Toolbelt.test.js
- src/utils.js
It fixes some saves that were broken by the release of the Mining update. The migration of old save data was incomplete, so we needed to patch what was forgotten previously.
Run the contents of this snippet in your JS console and reload: https://gist.github.com/jeremyckahn/83eeb8baddd9b1b911679c32e8c0dedc
All should work well, and there should be no errors.
> Mining update hotfix

- public/index.html
This is another attempt at #216: Making Google Analytics work on www.farmhand.life.
I was actually able to test it this time! As of this writing, this is running at https://www.farmhand.life/ via manual promotion to Prod in Vercel. After loading the page, I was able to see my session appear in Google Analytics: 
To validate, take a look at the Analytics dashboard for farmhand.life and see your session show up.
> Make analytics work on all production domains

- .github/workflows/notify-discord-about-update.yml
- README.md
- package.json
- src/components/Home/Home.js
This changes a number of references from https://jeremyckahn.github.io/farmhand/ to https://www.farmhand.life/. We should prefer the latter, as it is more memorable and inclusive of all who work on the game.
I'm not sure that there's a great way to? I don't think this will break anything either way, though.
> Use farmhand.life as primary prod URL

- package.json
- src/components/CowPen/CowPen.js
- src/components/CowPenContextMenu/CowPenContextMenu.test.js
- src/components/KeybindingsView/KeybindingsView.js
- src/components/KeybindingsView/KeybindingsView.test.js
- src/components/KeybindingsView/index.js
- src/components/OnlinePeersView/OnlinePeersView.test.js
- src/components/OnlinePeersView/index.js
- src/components/Plot/Plot.js
- src/test-utils/index.js
- src/utils.test.js
Ticket: #239
This PR is a followup to a configuration gap that surfaced in @UnquietBones' PR: https://github.com/jeremyckahn/farmhand/pull/238#discussion_r777235755
It changes the `pre-commit` hook to run ESLint and Prettier for all commits for all branches, but only run the tests on the `develop` branch. The CI system will the run the tests for all pushes regardless, so any broken tests should still be caught pretty quickly.
This PR also runs `npm run prettier` to clean up all the style violations that were not caught previously because of this gap.
Branch off of `jeremyckahn/239_format-and-lint-all-branches`, make a change that breaks Prettier rules, attempt to commit it, and observe that it is automatically fixed before being committed.
Are there any other checks that we should run in …
> chore: [#239] Format and lint all branches

- src/components/Field/Field.js
- src/components/Field/Field.test.js
- src/components/Plot/Plot.sass
- src/event-handlers.js
This PR implements #236. It's a UX improvement that prevents the player's field range settings from being changed by selecting the Scarecrow or the Sprinkler. It also improves how field ranges are displayed.
Use different items and tools at different ranges, go back and forth between selecting the Scarecrow and Sprinkler items, and see if the interaction feels intuitive.
- How well do the range colors work? Anything else that should change with the display of the ranges?
- Does this new UX of the different items having different ranges feel good?
> Decouple static ranges from slider

- README.md
- src/Farmhand.js
- src/components/SettingsView/SettingsView.js
- src/components/SettingsView/SettingsView.test.js
- src/constants.js
- src/event-handlers.js
- src/event-handlers.test.js
- src/utils.js
This adds an option to the Settings page to hide the Home screen. It is off by default and changes persist into the saved game state.
When the option is toggled on, HOME is removed as a navigation option and if the user is on the Home page it will move them to the next view (which is currently the SHOP).
When the page is first loaded or reloaded with the Home view hidden, the program will move to the next view in the list as above (is not hardcoded to SHOP).
Manual testing by opening settings and toggling the option.
If you toggle it off and are shifted over to the SHOP, it will not shift you back to HOME if you toggle it off again. Not sure if users will care?
> feat:[closes #234] Hide Home Screen option

- src/reducers.js
- src/utils.js
For #255, this PR changes cow sales such that they all count towards revenue figures. Per what was originally reported, a poor design choice on my part resulted in a broken-feeling experience. After some debugging and experimentation, I discovered that simply removing the undesirable logic resulted in cow sales working in an intuitive and appropriate manner, as cows are worth $0 the day they are purchased. They gain value with age: https://github.com/jeremyckahn/farmhand/blob/9e9997d81291311ffb86b90daf6fe32f9426cee5/src/utils.js#L607-L621
Sell any cow and see that its value is reflected accurately in "Today's Revenue" in the Farm Stats dialogue.
> Make all cow sales count towards revenue

- src/Farmhand.js
- src/trystero-handlers.js
This PR fixes a crash I noticed in Production where a peer had `null` data. Somehow a peer was connecting to the room, but the my client never received  their metadata before I initiated a trade.
For reference, peers start off with `null` data: https://github.com/jeremyckahn/farmhand/blob/015d288700eba456294cf5daf7db579b8abd9e71/src/reducers.js#L2111-L2116
Shortly thereafter (asynchronously), this data gets populated as the peers in the room broadcast their state:
https://github.com/jeremyckahn/farmhand/blob/015d288700eba456294cf5daf7db579b8abd9e71/src/Farmhand.js#L703-L706
https://github.com/jeremyckahn/farmhand/blob/015d288700eba456294cf5daf7db579b8abd9e71/src/trystero-handlers.js#L21-L23
https://github.com/jeremyckahn/farmhand/blob/015d288700eba456294cf5daf7db579b8abd9e71/src/reducers.j …
> fix: handle null peer data in cow trades

- src/components/Achievement/Achievement.js
- src/components/Achievement/Achievement.test.js
converts the Achievement test to use react testing library as part of the #269 effort. i also converted a proptype from an object to a shape because when i went to write the test i wasn't sure what achievement should look like without digging into the use.
tests need to pass
n/a
n/a
> convert Achievement test from enzyme to rtl

- src/components/AccountingView/AccountingView.test.js
Convert spec file from enzyme to using testing-library.
if unit tests pass, it's good to go!
This isn't quite 100% coverage, but it's pretty close. There are currently two components in the `AccountingView.js` file and I think if the other was split out the coverage would be easier to achieve.
> refactor: convert AccountingView spec from enzyme to testing-library

- src/components/Farmhand/Farmhand.sass
- src/components/Field/Field.js
- src/components/Field/Field.sass
- src/components/Plot/Plot.sass
- src/components/QuickSelect/QuickSelect.sass
This PR changes the Field to make a better use of screen space on wider screens. It simplifies the overall responsive design of the UI to leverage `orientation` media queries rather than specific pixel breakpoints. 
View the Field in a variety of scenarios (portrait, landscape, menu open/closed) on a variety of devices (desktop/laptop, mobile, tablet) and make sure everything is accessible.
There are areas where this could still be improved, but I think it's a net positive so far!
<details>
<summary>Screenshots</summary>
</details>
> feat: Field landscape dislay

- src/components/Field/Field.sass
- src/components/QuickSelect/QuickSelect.sass
- src/styles/variables.sass
It reveals my hubris. 🙃
It also fixes a minor big introduced by #302 wherein the QuickSelect overlapped the End Day button on smaller screens in landscape orientation.
Play the game on a smaller screen like an iPhone SE (emulated is fine) and observe that a full tool bar does not overlap the End Day button.
I'm going to stop merging PRs without review...
Before this change:
After this change:
> fix: Do not overlap End Day button with QuickSelect

- src/components/Field/Field.sass
This PR addressed the need described in #308 by limiting the field size for wider screens.
Open the field in a variety of screen sizes and ensure that the field is generally fully visible and accessible. It won't always be perfect, but it should at least fit on the screen reasonably well.
Enabling greater zoom-out was much harder than I anticipated due to issues similar to https://github.com/prc5/react-zoom-pan-pinch/issues/84. We have a workaround in place to deal with this here: https://github.com/jeremyckahn/farmhand/blob/4f8970728c3958ccc1a1f4406b035d74a9608c53/src/components/Field/Field.js#L376-L382
Ideally we could simply remove the `if (scale >= 1)` check, but that crashes the game. 🙁
Before this PR:
After this PR:
> fix: [#308] limit field size on wider screens

- src/components/Workshop/getUpgradesAvailable.js
- src/components/Workshop/getUpgradesAvailable.test.js
Fixes tool upgrades not showing up in the forge due to expectation of data being in a different shape than it actually was
Get to the point of unlocking ore recipes and then verify that the tool upgrades are also available. Compare this to prod where the tool upgrades do not show up.
Here's a save that can be used 
[farmhand-2022-07-16.json.zip](https://github.com/jeremyckahn/farmhand/files/9126360/farmhand-2022-07-16.json.zip)
screenshot of tool upgrades showing up in local server running this branch
> update for proper data

- src/components/Field/Field.sass
- src/components/QuickSelect/QuickSelect.sass
- src/components/Stage/Stage.sass
It builds on #309, #302, and #300 by making more space for the Field and QuickSelect elements on more screens under more conditions.
View the Field in a variety of conditions (portrait and landscape mode, menu open and closed) and ensure that all critical UI is reasonably accessible.
Someday I will get this part of the design right...
<details>
<summary>Click to see screenshots</summary>
</details>
> feat: Improve responsive Field sizing

- src/components/Home/Home.js
- src/components/Recipe/Recipe.js
It addresses #313 by rendering recipe descriptions in the Workshop.
It also adds a bit of info about weeds on the Home screen.
Verify that Fertilizer and Compost descriptions appear in the Workshop and that the new info about weeds appears on the Home screen.
> feat: Show Recipe description

- src/components/Farmhand/Farmhand.test.js
- src/shell/notifications.test.js
For #269, this PR updates the validation of cow pen purchase notifications to be done with React Testing Library instead of Enzyme.
Observe that the tests pass.
This finally removes Enzyme from `Farmhand.test.js`! We are making progress. The work done in #298 made this much easier, so thank you @lstebner for that!
> refactor: Validate cow pen purchase notifications with React Testing Library

- src/components/Farmhand/Farmhand.js
- src/components/Plot/Plot.js
- src/components/Plot/Plot.rtl.test.js
- src/components/Stage/Stage.js
- src/game-logic/field-purchase.test.js
- src/game-logic/item-purchase.test.js
- src/game-logic/item-sell.test.js
- src/handlers/ui-events.test.js
For #269, this converts some tests related to buying and selling to use React Testing Library
Ensure the tests pass.
> refactor: Convert purchase and sale tests to use React Testing Library

- .env
- .env.development.local
- src/components/Shop/Shop.js
- src/components/Toolbelt/Toolbelt.test.js
- src/components/Workshop/Workshop.js
- src/data/achievements.js
- src/data/achievements.test.js
- src/data/levels.js
- src/data/tools.js
This PR removes the `MINING` feature flag, which is no longer used.
Ensure that the mining-related functionality still works.
~I'm not actually sure how any of this was working with the flag still in place. It's not clear how the flag is being enabled in Production. :grimacing:~ I figured it out: https://github.com/jeremyckahn/farmhand/commit/97ca7eef988c28d84f480a5709806af43250fd56
> refactor: Remove `MINING` feature flag

- src/components/Farmhand/Farmhand.js
- src/config.js
This PR improves peer-to-peer connectivity by using a [public relay server](https://www.metered.ca/tools/openrelay/) when direct connections fail. This address the problem of peers that never connect successfully.
This video explains some of the networking specifics better than I can: https://www.youtube.com/watch?v=4dLJmZOcWFc
It depends on whether you experience peer connection issues without this change. Personally, I was unable to connect to peers when on a mobile network. After testing this in the preview environment, my mobile device was able to connect successfully.
This change depends on a third-party service that we don't control (https://www.metered.ca/tools/openrelay/). Ideally we'd host our own server to provide the relay functionality, but that would cost money. I'm open to …
> feat: Use relay servers for improved peer connectivity

- src/components/Farmhand/Farmhand.js
- src/data/achievements.js
This PR addresses [a bug report from Reddit](https://www.reddit.com/r/incremental_games/comments/xxda0f/comment/iref8k9/?utm_source=reddit&utm_medium=web2x&context=3):
> you can use shift+4 way before unlocking the shovel, used it to pay the loans day1 and get started
Start a new Farmhand game and ensure that the Shovel can't be accessed via the Shift + 4 keyboard shortcut. Once the Shovel is unlocked, ensure that it can be accessed via the Shift + 4 keyboard shortcut.
> fix: Prevent accessing Shovel via keyboard shortcut when it is unavailable

- src/components/QuantityInput/QuantityInput.js
fixes a bug where the QuantityInput would start to count up while pressing the decrement button. it doesn't really do much other than move away from using `--value` in favor of a more functional approach which seems to fix the problem.
load up a fresh game and sell all but one of the jack-o-lanterns that are currently being put in the inventory (since it's october). then press 'decrement' and notice it does not start counting up like production currently is doing. after selling the jack-o-lanterns some fertilizer will have appeared, so press increment and decrement on that and make sure it is still functioning as expecting with the wrapping behavior.
this bug was reported in discord #bug-reports channel
> fix quantity inputs allowing unacceptable values

- src/game-logic/reducers/sellItem.js
- src/game-logic/reducers/sellItem.test.js
This PR addresses an exploit that was [reported by M8theone on Discord](https://discord.com/channels/714539345050075176/822068921653788683/1039629286740611192):
> Currently selling seeds counts towards the all time total revenue
- Sell a seed and observe that neither "Today's Revenue" or "All-Time Total Revenue" stats change.
- Sell a non-seed item and observe that both "Today's Revenue" or "All-Time Total Revenue" stats increase appropriately.
> fix: [fixes #340] prevent seed sales from counting as revenue

- src/game-logic/reducers/sellItem.js
- src/game-logic/reducers/sellItem.test.js
This PR fixes #342 by ensuring that sale bonuses (as earned by the "Millionaire" and "Billionaire" achievements) only apply to farm products (like milk, grown crops, and crafted recipes).
Ensure that only grown crops and milk receive sale bonuses. You can test this on a fresh save by running this in the console:
```js
farmhand.setState({
inventory: [
{ id: "carrot-seed", quantity: 10 },
{ id: "carrot", quantity: 10 },
{ id: "carrot-soup", quantity: 10 },
{ id: "scarecrow", quantity: 10 },
],
loanBalance: 0,
completedAchievements: { "i-am-rich-3": true },
});
```
Ensure that Carrot, Carrot Seed, and Scarecrow all sell for the amount that they indicate. You can run the same code but with `completedAchievements: {}` to see how the behavior compares to when a sale bonus is not applied.
> fix: [fixes #342] Only apply sale bonuses to farm products

- src/components/Plot/Plot.sass
Based on [discussion in Discord](https://discord.com/channels/714539345050075176/847884323330850847/1040121234454757377), this PR changes how highlighted plots are displayed when the watering can is selected.
Select the watering can and hover over some plots. Change the range slider to increase/decrease the watering range.
> feat: Improve display of highlighted plots when watering

- src/components/Home/Home.js
This PR adds a link to Farmhand Go!'s Steam store page.
Make sure the link works and that the copy reads well.
> feat: Add Farmhand Go! Steam link

- .github/workflows/ci.yml
This PR updates the CI job to run the JSDoc build process to prevent JSDoc errors from being merged to stable branches.
Ensure that the CI job for this PR succeeds.
This was made as a result of JSDoc errors breaking a production build: https://github.com/jeremyckahn/farmhand/actions/runs/3602696645/jobs/6069975304
> chore: Build docs in CI

- src/constants.js
- src/game-logic/reducers/applyCrows.js
- src/game-logic/reducers/applyCrows.test.js
- src/game-logic/reducers/processNerfs.test.js
- src/templates.js
this change alters crow logic so that there is a maximum number of crows that can be spawned and those crows then pick from plots that currently have crops at random to destroy them. previously, all plots were subject to an attack based on a random chance which could result in a lot of crops being destroyed at once.
this change also updates the notification after crows destroy plots to mention the number of plots destroyed in a single notification instead of one per plot destroyed which would often result in a flood of notifications that were hard to read before they would disappear.
Plant crops and then advance days. If there is no scarecrow, you should see some crops destroyed and the new notification. There is also a random chance no crops will be destroyed over night. When a scarecrow …
> crow logic updates

- .github/workflows/run-release.yml
This PR temporarily disable MacOS builds. There is a new build breakage that's [causing the Release workflow to ultimately break](https://github.com/jeremyckahn/farmhand/actions/runs/3813347452/jobs/6487066812).
Run a release and hope that nothing breaks. 🙃
> fix: Disable MacOS builds

- src/components/Farmhand/Farmhand.js
It adds a scarecrow at the beginning of the game by including an item object at inventory of initial state
By running a new game, and the scarecrow will be seen in the inventory. You can also see the scarecrow at the side menu in the fields tab.
Currently the scarecrow is added but the $500 at the start still remains. Should it be reduced by $160 to account for the scarecrow?
Should addItemToInventory be used instead of "hardcoding" it into the initial state?
> [closes #259] added scarecrow to inventory at initial state of the game

- src/data/levels.js
It prevents Olive Seed from being available at the start of the game.
Ensure that Olive Seeds are not available for brand new save files.
This is a hotfix for #377.
> fix: Prevent Olive Seed from being available at the start of the game

- src/components/CowCard/Subheader/Subheader.js
- src/game-logic/reducers/changeCowBreedingPenResident.js
- src/game-logic/reducers/changeCowBreedingPenResident.test.js
- src/handlers/peer-events.js
This PR is a **speculative** fix for #385. I wasn't able to reproduce the bug that was reported, but after spending some time with the code I believe I've identified a possible race condition related to cow trading. This race condition could lead to the breeding pen data referencing cows that don't exist in the inventory, thus corrupting the data. This PR introduces a check to ensure that such an invalid reference is never made.
Ensure that there are no regressions related to moving cows into or out of the breeding pen or cow trading.
I plan to close #385 by merging this. I couldn't reproduce it and there's not much value in leaving the ticket open since we can't prove a negative. If this issue resurfaces, we can always reopen the ticket.
> fix: [fixes #385] Ensure valid breeding pen references

- src/components/Cellar/Keg.js
- src/constants.js
- src/data/crops/carrot.js
- src/game-logic/reducers/processCellar.js
- src/game-logic/reducers/processCellarSpoilage.js
- src/game-logic/reducers/processCellarSpoilage.test.js
- src/templates.js
- src/test-utils/stubs/getKegStub.js
- src/utils/getKegSpoilageRate.js
- src/utils/getKegSpoilageRate.test.js
This PR implements keg spoilage. The longer the player holds onto a keg, the greater the chance becomes for that keg to be spoiled and lost.
Follow setup steps similar to #413 to populate your cellar:
1. Give yourself enough money to buy a Cellar:
```js
farmhand.setState({ money: 1_000_000 })
```
2. Purchase a Cellar in the Shop's Upgrades tab.
3. Navigate to the Cellar's screen (at the end of the screen sequence).
4. Give yourself a lot of salt:
```js
farmhand.setState({ inventory: [...farmhand.state.inventory, { id: 'salt', quantity: 1000 }]})
```
5. Make a Fermented Carrot (or whatever crops you have available).
6. Advance the days to see the keg's spoilage rate go up. Eventually the keg will spoil with a new day and it should be removed from the cellar inventory.
This PR needs some …
> feat(Cellar): [closes #418] Keg spoilage

- src/components/Farmhand/Farmhand.js
- src/game-logic/reducers/purchaseCellar.js
- src/game-logic/reducers/purchaseCellar.test.js
- src/game-logic/reducers/purchaseCowPen.js
- src/game-logic/reducers/purchaseCowPen.test.js
- src/game-logic/reducers/showNotification.js
- src/shell/notifications.test.js
- src/templates.js
This PR shows a notification to the player when a cellar is purchased.
This PR also refactors how cow pen notifications are shown and improves some type definitions.
Purchase a cellar and verify that a notification is shown.
> feat(Cellar): Show purchase notification

- package-lock.json
- package.json
This PR updates Farmhand to use https://github.com/jeremyckahn/shifty/releases/tag/3.0.1.
Ensure that cow and number animations work as they did before.
This isn't a necessary upgrade. I'm mostly doing it to validate the latest release of Shifty.
> chore(deps): Use shifty@3.0.1

- .github/workflows/ci.yml
- package.json
- src/components/AppBar/AppBar.test.js
- src/components/CowCard/CowCard.test.js
- src/components/CowPen/CowPen.test.js
- src/components/CowPenContextMenu/CowPenContextMenu.test.js
- src/components/DebugMenu/DebugMenu.test.js
- src/components/Farmhand/Farmhand.js
- src/components/Farmhand/FarmhandReducers.js
- src/components/Field/Field.test.js
- src/components/Item/Item.js
- src/components/Navigation/Navigation.test.js
- src/components/Plot/Plot.rtl.test.js
- src/components/Plot/Plot.test.js
- src/components/QuantityInput/QuantityInput.test.js
- src/components/QuickSelect/QuickSelect.test.js
- src/components/SettingsView/SettingsView.test.js
- src/components/Shop/Shop.test.js
- src/components/Toolbelt/Toolbelt.js
- src/game-logic/reducers/fertilizePlot.test.js
- src/index.js
- src/react-app-env.d.ts
- src/utils/index.js
- src/utils/noop.js
This PR:
- Fixes all of the errors in `src/components/Farmhand/Farmhand.js`
- This required some considerable refactoring switching to patterns that are statically analyzable
- Updates CI job to check types
- Currently this does not cause a build failure and is strictly informational
- Uses a global `noop` util
This is a pure refactor, so a broad smoke test for regressions should be all that's necessary.
I don't really love the new `FarmhandReducers` pattern, but I couldn't find any other way to bind reducers in a statically analyzable way.
> refactor(types): Make `Farmhand` component type-safe

- src/data/achievements.js
- src/game-logic/reducers/applyCrows.test.js
- src/game-logic/reducers/helpers.js
- src/utils/findInField.js
- src/utils/findInField.test.js
- src/utils/index.js
For #430, this PR fixes an implementation bug that manifested in Scarecrows not working if they weren't the first plot in a Field row.
Place a Scarecrow somewhere in the middle of the Field and ensure that crows do not attack when ending the day.
It seems that this bug may have been introduced here: https://github.com/jeremyckahn/farmhand/pull/427/files#diff-ebd8554ec43b07366bd40d16b09d1d063d9e8d5921fa30de4eb80bffdf82668dR718-R727
In any case, this issue wasn't noticed until #427 was shipped.
> fix(utils): [closes #430] Make `findInField` return the correct plot

- package-lock.json
- package.json
- src/components/Farmhand/Farmhand.js
- src/components/LogView/LogView.js
- src/components/NotificationSystem/NotificationSystem.js
- src/game-logic/reducers/showNotification.js
- src/game-logic/reducers/updatePeer.js
- src/game-logic/reducers/updatePeer.test.js
- src/handlers/peer-events.js
- src/index.js
- src/templates.js
- src/test-utils/stubs/cowStub.js
- src/test-utils/stubs/peerMetadataStub.js
- src/utils/index.js
For #432, this PR adds a notification that is shown when an online peer offers a cow for trade. When the notification is clicked, the "Active Players" dialog is opened.
This PR also:
- Updates Trystero to the latest version and increases tracker redundancy for improved peer connectivity.
- Gives clickable notifications the `pointer: cursor` style.
Set up two peers (they can be on the same computer but in different browsers) and join the same online room. Once peers are connected, offer a cow for trade. Observe that the other peer gets a notification like the one pictured below.
> feat(online) [for #432] "Cow offered" notification

- src/components/CowCard/CowCard.js
- src/components/CowCard/Subheader/Subheader.js
- src/components/CowCard/Subheader/Subheader.test.js
- src/handlers/ui-events.js
- src/test-utils/stubs/cowStub.js
- src/utils/index.js
For #442 (reported by @jmmullins), this PR changes how cows offered by online peers are presented. Previously, cows were incorrectly shown to peers as if they were for sale (such as when they are first purchased). Now, they are correctly shown with their sale value.
This PR also updates the `CowCard` and its helper `Subheader` component files to be type-safe.
1. Ensure that cows for sale show their "Price": 
2. Ensure that cows in the cow pen inventory show their "Value": 
3. Ensure that cows being offered show their "Value": 
4. Ensure that cows that can be traded for show their "Value": 
I highly recommend disabling whitespace changes when reviewing this PR.
> fix(online): [fixes #442] Show correct peer cow state

- src/game-logic/reducers/sellItem.test.js
- src/utils/isItemAFarmProduct.js
For #460, this PR gives the player one experience point for selling Coal, ores, and stones.
Sell Coal, any ore, and any stone (Stone or Salt Rock items) and observe that you receive 1 experience point each.
> feat(experience): [closes #460] Grant experience for selling coal, ores, and stones

- src/components/CowCard/CowCard.js
- src/components/CowPen/CowPen.js
- src/components/Farmhand/Farmhand.js
- src/constants.js
- src/hooks/useMountState/index.ts
- src/hooks/useMountState/useMountState.ts
- src/utils/index.js
This PR fixes two issues that I discovered during development:
1. The "Show the Home Screen" setting wasn't working properly. The setting's value was persisting, but the app bootup sequence didn't properly account for it. The end result is that the app booted up in an invalid state and broke some views.
2. There was a spurious warning being logged if the player cycled through views too quickly after booting. This PR improves the asynchronous handling of the dynamic cow image generation to prevent this warning.
1. Open the Settings dialog, disable "Show the Home Screen," save the game, and reboot. Verify that you can cycle through all of the views without seeing any errors.
2. Cycle through the Cows view as quickly as you can and verify that there are no errors or warnings in the browser …
> fix(settings): Prevent invalid state when booting save with Home screen disabled

- src/components/CowCard/Subheader/Subheader.js
- src/components/CowCard/Subheader/Subheader.test.js
Closes #443 by displaying age of cows offered for trade
New tests added, one of which fails without this Subheader.js change
Are the tests too much?
> feat: show age for cows offered for trade (#443)

- src/components/AnimatedNumber/AnimatedNumber.js
- src/components/Elements/index.js
- src/components/Farmhand/Farmhand.sass
- src/components/Item/Item.js
- src/components/QuantityInput/QuantityInput.js
- src/components/QuantityInput/QuantityInput.sass
- src/mui-theme.js
This PR improves a regression that I believe was introduced by #470. It improves the display of the `QuantityInput` component.
Ensure that quantity input looks and works correctly throughout the game.
Before:
After:
> feat(ui): Improve `QuantityInput` spacing

- .env
- .env.development.local
- src/components/Shop/Shop.js
- src/data/recipes.js
This is a housekeeping PR to remove the `KEGS` flag, since that feature is released and stable.
Ensure that the Cellar feature still works.
> chore(feature-flag): Remove `KEGS` flag

- api-etc/constants.js
- api/get-market-data.js
- src/common/constants.js
- src/components/Farmhand/Farmhand.js
- src/components/Navigation/Navigation.js
- src/components/OnlinePeersView/OnlinePeersView.js
- src/constants.js
- src/game-logic/reducers/addPeer.js
- src/game-logic/reducers/removePeer.js
- src/strings.js
This PR optimizes multiplayer API usage by eliminating polling. Rather than using the Vercel-based central API to determine room occupancy, the number of connected peers is used.
:bangbang: Please **DO NOT** test this in the default `global` room, as that affects Production data. Instead, use another room such as `global-test`.
This change is needed because Farmhand is getting so much multiplayer activity that we're exceeding the capacity of the free Vercel tier that is powering it.
> feat(multiplayer): Optimize API usage

- src/components/Navigation/DayAndProgressContainer.js
- src/config.js
- src/data/levels.js
- src/templates.js
This PR fixes [an issue that was discovered by a player](https://discord.com/channels/714539345050075176/714539345637408793/1251318040122101903): The Forest unlock notification was being shown in Production. This feature is still in development, so this notification should be withheld by a feature flag.
This PR also improves the experience gauge tooltip by showing an alternate label when there is one point left to reach the next level.
You can use [this test save](https://gist.github.com/jeremyckahn/0d3fd8c49a8ce41d036974496e354c93) to aid in validation.
- In the test save linked above, this can be done by selling the Carrot that is in the inventory
----------
> fix(forest): Keep Forest unlock notification behind feature flag

- src/constants.js
- src/game-logic/reducers/purchaseCombine.test.js
Per feedback from [M8theone on Discord](https://discord.com/channels/714539345050075176/722286738344640552/1273256123486703718), this PR modifies the costs of various upgrades:
- Increase second and third Field upgrade costs (to $5,000 and $20,000)
- Increase second and third Cow Pen upgrade costs (to $10,000 and $50,000)
- Decrease Combine Harvester cost to $250,000
- Decrease Smelter cost to $250,000
- Increase second and third Cellar upgrades (to $750,000 and $2,000,000)
Verify that the costs of relevant upgrades matches what's listed above.
I'll wait to get feedback from M8theone about this change before moving it along.
> feat(#505): Re-balance upgrade costs

- src/components/CowCard/Subheader/Subheader.js
> Fix missing space between hugging machine and and

- package.json
This PR fixes a regression introduced by #510 wherein build artifacts are not included in `npm publish`.
This, along with https://github.com/jeremyckahn/farmhand/commit/77630bf6b822f1d12a48b503c4386e17f76a8b70, should make historical versions of Farmhand hosted by UNPKG work again.
Merge, release, and see if https://unpkg.com/browse/@jeremyckahn/farmhand/build/ serves anything.
> fix(package): Include `dist` directory when publishing

- package-lock.json
- package.json
- src/index.js
For #531, this PR updates Farmhand to use actively-maintained font packages.
> chore(deps): [closes #531] Swap `typeface-*` packages for `@fontsource/*`

- src/game-logic/reducers/changeCowBreedingPenResident.js
- src/utils/index.js
- src/utils/index.test.js
This is a speculative mitigation for #546. If a corrupt `cowBreedingPen` state is detected when loading a save file, it is automatically fixed.
This fixes an error state that has no known steps to reproduce, so all we can really do is verify that the tests pass and that there are no regressions.
This may not be strictly needed as #547 is intended to fix the root cause of #546. However, since the issue could not be reproduced, #547 cannot be verified to effectively solve the problem. This PR is more of a fallback solution to enable users to fix their game state by reloading the page.
> fix(closes #546): Detect and fix corrupt cowBreedingPen state

- .github/workflows/run-release.yml
This PR attempts to fix an issue where an extraneous `0.0.0` tag is created during the release process.
Make a production release and see if the problem is resolved.
This is a Gemini-suggested fix and I have no idea if it will work. 🤷‍♂️
> fix(ci): Prevent creation of `0.0.0` version during release process
